// <auto-generated />
using System;
using Funcionarios.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Funcionarios.API.Migrations
{
    [DbContext(typeof(FuncionarioAPIDbContext))]
    partial class FuncionarioAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Funcionarios.API.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("cdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdMatricula"), 1L, 1);

                    b.Property<string>("UO")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("cdFuncao")
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    b.Property<string>("dsFuncao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("dsNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("dtInicio")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2");

                    b.HasKey("cdMatricula");

                    b.ToTable("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
